### ISSUE TITLE
Extension overrides Super+L (tiles active window)

### ISSUE THREAD

**Issue by HansAdema** [emasab/shelltile#32]
Since the last release, Super+L (which I mapped to lock the screen) is overridden by ShellTile. With the extension enabled, Super+L causes the active window to be tiled to the right of the screen.

## Reproduction steps
1. Set the keyboard shortcut for Lock Screen to Super+L
1. Enable ShellTile (default settings)
1. Hit Super+L

## My Stack
- Ubuntu Gnome 16.04
- Gnome 3.18.5

**Comment by ryanleesipes** [comment]
All the super + arrow keys are killed by this too, which is unfortunate, as that is the way that I typically manage my window tiling. (Super+Left in order to place it on the left side of the screen, same but with right).

**Comment by HansAdema** [comment]
@ryanleesipes I can confirm that happens to me too (I just noticed it a few hours ago).

**Comment by emasab** [comment]
I've removed the super+l super+k super+j and super+i keybindings.
I didn't notice of the lock combination because I use Ctrl+Alt+l, but some users have the super key mapped to Ctrl+Alt. Ctrl+arrows are there by design and they do the same thing than the default, but they're handled by ShellTile. @ryanleesipes those keybindings don't work with the extension enabled ?

**Comment by IvanAlekseevichPopov** [comment]
Same problem. In fedora super+l is default for lock screen. And all works fine before update.

**Comment by randoogle** [comment]
Perhaps the shortcut keys could be configurable, rather than trying to force everyone to use the same ones? Also, might I suggest using Super + keypad keys? So Super + 6 would be the right half, Super + 4 would be the left. This has the added benefit of allowing for corner windows in an intuitive way. For instance, Super + 9 would be the upper right corner and Super + 3 would be the bottom corner. Super + 5 could be maximize, I suppose.

**Comment by emasab** [comment]
It works similiar to that, <super>+up and left tiles to the upper left corner. Keypad is not a good choice because in many laptop keyboards it's missing or uses the additional fn key. In the meantime I'm going to remove the shortcuts and restore the default. The latest push does this.
