### ISSUE TITLE
Keybindings being overwritten >:(

### ISSUE THREAD

**Issue by TinfoilPancakes** [emasab/shelltile#33]
I'm not sure if you're aware but your extension rebinds my super + (i, j, k, l) and is **_**seriously frustrating**_**. Super + L is default for lock screen btw, **please check before you hard-code keybindings**, or just don't.
I saw from your commits that you have fixed this but, unfortunately this is not reflecting even after re-installing. I like your extension but I really hate that you can just rebind things without warning -__-

I'd dig around to see the proper API for adding keybindings into the gnome settings menu.

Pls don't do it again.

**Comment by AlexWayfer** [comment]
@TinfoilPancakes Try `Alt+F2` → `r` → `Enter` (reload GNOME shell), or just restart session/computer, please.

Reloading helped for me.

**Comment by TinfoilPancakes** [comment]
@AlexWayfer Thanks for advice Alex,

Unfortunately I already did all of these things in my attempt to fix the keybindings. Sadly none of these solved the issue correctly. It took me almost a day to figure out that it was the shelltile extension. I have fixed the problem for myself by editing the extension.js on my machine to remove the keybinds. Just a heads up to the author or anyone else.

**Comment by emasab** [comment]
Sorry for the inconvenience,on Ubuntu super+l doesn't lock the screen, but ctrl+alt+l does, so it's difficult to set a default. At first I removed those keybindings (super+lkji) because they were superfluous, then I removed the super+arrows too because, on fedora and arch (not on ubuntu), the default keybindings of gnome shell could be removed but the new keybindings were not registered. 

If you still have that bug you have to install the version on github, because the version on extensions.gnome.org is waiting for review, or copy the extension.js file and restart.

What to do now ? I wanted to have a default keybinding, but given the heterogeneous distributions, I think it's not possible.

**Comment by TinfoilPancakes** [comment]
@emasab I'm not too familiar with Gnome & Extension Development however, is there a way to query gsettings or gconf or whatever to find the binding for the proper action (eg "View split on left" or "View split on right") and bind to those?

**Comment by emasab** [comment]
The extensions did this: first it removed the bindings on gconf for org.gnome.desktop.wm.keybindings.maximize, org.gnome.desktop.wm.keybindings.unmaximize, org.gnome.mutter.keybindings.toggle-tiled-left, org.gnome.mutter.keybindings.toggle-tiled-right. These on ubuntu are associated with super+arrows. 

This was necessary because otherwise the wm doesn't let you register the same keybindings. After that it tried to register the super+arrows keybindings with global.display.grab_accelerator (and the other ones that I've removed). 

On the installations that experienced the problem, the first succeded, in fact super+arrows didn't work anymore, but the registration of the same keybindings by shelltile did not succeed. It seems like there was something else than gnome and mutter holding those keybindings, but this shouldn't be possible. Or otherwise gnome shell didn't notice immediately that those were removed and denied the registration.

Anyway this doesn't seem a viable solution anymore, I'll way until I find a less/not hacky solution.

**Comment by dbrodie** [comment]
Is there anywhere where the keybindings are listed and maybe configurable? I only found out about some of these keybindings by reading the GitHub issues.

**Comment by emasab** [comment]
Sorry, keybindings are gone :)  ... until I find a way to make them work on every distribution. 
If you want to try them, you can clone
https://github.com/emasab/shelltile/tree/2bba1d48ba672fc06dac0c78caf5dad5e8f41cd8, but they should work only on Ubuntu, there where problems reported on Fedora and Arch. The shortcuts are Super+arrows, Super+double up for top-half tiling.

**Comment by coredump** [comment]
@emasab I got here trying to figure out why the keybindings weren't working :P 

Would it be possible to add a config for the keybinds on the extension? So each person that wants to use the keybinds has to set it?

I would think about non standard bindings like Ctrl+Super + arrows or even symbols like `[ ] '`
